### ISSUE TITLE
Could you tag/release the docker image

### ISSUE THREAD

**Issue by obeyler** [huaweicloud/external-sfs#23]
**FEATURE REQUEST**:
Could you tag/release the docker image ?
https://quay.io/repository/huaweicloud/sfs-provisioner?tab=tags
keep only 'latest' tag is not a good idea and should not be use in production env
please publish version with last PR as it contains cve fix.

**Comment by obeyler** [comment]
@edisonxiang

**Comment by edisonxiang** [comment]
Hey @obeyler, I pushed a new image `quay.io/huaweicloud/sfs-provisioner:v1.0` which includes your commit. Could you try it? Thanks.

**Comment by obeyler** [comment]
No Pb I test it !
Thanks for the tag
